### PR TITLE
Update to handle callbacks with multiple arguments.

### PR DESCRIPTION
**Pull request by riggs**
Also, move from using `arguments` to the spread operator to be more explicit.

### CODE REVIEW

**Comment by tfoxy** [comment]
Hi. Thanks fo the PR. There is an error in the tests. `self` is not defined. I think the error should be solved if you rename `thisArg` to `self`.

If you fix the error, I can merge the changes.

I also like the solution proposed by @amio, as it has a more predictable behaviour. I will add an option to the constructor so any of the two solutions can be used.

**Comment by riggs** [comment]
Hmm, strange, it looks like the version pushed to npm is a different version of the codebase, ever so slightly. I'll update my changes to match the current version.

**Comment by riggs** [comment]
It looks like the current failure is because you're testing against a version of [Chrome from 2014](https://en.wikipedia.org/wiki/Google_Chrome_release_history):

`Session info: chrome=37.0.2062.120`

The spread operator has been [supported since Chrome 46](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator).

**Comment by tfoxy** [comment]
I will try to update the chrome version used by travis by using trusty.

**Comment by tfoxy** [comment]
I updated chrome to the current stable version. Can you rebase the PR?

**Comment by riggs** [comment]
Done.

**Comment by tfoxy** [comment]
Merged! I will release the new version tomorrow.

**Comment by riggs** [comment]
Awesome! Thanks so much!

**Comment by riggs** [comment]
BTW, between your library and the babel [async-to-generator transform](http://babeljs.io/docs/plugins/transform-async-to-generator/) plugin, I'm successfully using async/await wrapped chrome APIs, which is such a huge improvement over callback-hell.

**Comment by tfoxy** [comment]
Yeah, it's a shame that the api does not have promises by default. It was very common for me to have multiple callbacks. With async/await syntax I would think it's even simpler. And it's not necessary to use Q or Bluebird for that.

v2 is now live. Thanks again for the PR.

**Pull request merged**
